<?php

namespace DaydreamLab\User\Notifications\User;

use Carbon\Carbon;
use DaydreamLab\User\Notifications\BaseNotification;
use Illuminate\Bus\Queueable;
use Psy\Command\ShowCommand;
use SimpleSoftwareIO\QrCode\Facades\QrCode;

class UserGetOtpCodeNotification extends BaseNotification
{
    use Queueable;

    protected $view = 'emails.User.GetOtp';

    protected $type = "OTP";

    protected $category = "User";

    protected $user;
    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($user, $creatorId = null)
    {
        parent::__construct($creatorId);
        $this->user = $user;
        $this->subject = $this->defaultSubject();
    }


    public function defaultSubject()
    {
        return '[零壹科技官方網站] 登入保護驗證';
    }


    public function defaultMailContent()
    {
        $expiredMin = $this->user->twofactor['otp']['expiredSecond'] / 60;

        $str = "親愛的零壹網站管理員：<br><br>";
        // $str .= "您好，您的帳號（{$this->user->email}）正在進行後台登入驗證，本次產生的驗證碼為：『{$this->user->twofactor['otp']['code']}』 <br><br>";
        $str .= "您好，您的帳號（<font style='display: none'>@</font>{$this->user->email}）正在進行後台登入驗證，本次產生的驗證碼為：";
        $str .= "
            <table width='100%'>
                <tbody>
                    <tr>
                        <td align='center' style='padding-top: 60px;padding-bottom: 60px;'>
                            <table width='194'>
                                <tbody>
                                    <tr>
                                        <td
                                            align='center'
                                            style='
                                                font-size: 44px;
                                                padding: 20px 30px;
                                                background-color: #eef5cc;
                                                line-height: 1;
                                                color: #abcd02;
                                            '
                                        >
                                            {$this->user->twofactor['otp']['code']}
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>";
        $str .= "為了保障您帳號的安全性，請在15分鐘內完成驗證，請勿外流。 <br><br>";
        $str .= "同時，若您近期沒有執行登入零壹官方網站後台，請儘速與網站管理團隊聯繫以保障帳號安全。<br><br>";

        $str .= "零壹科技官方網站";

        return $str;
    }


    public function defaultSmsContent($channelType)
    {
        return "您的零壹科技官方網站後台驗證碼為：{$this->user->twofactor['otp']['code']}，請在15分鐘內驗證完畢，謝謝。";
    }


    public function toXsms($notifiable)
    {
        return parent::toXsms($notifiable); // TODO: Change the autogenerated stub
    }


    public function getMailParams()
    {
        return [
            'content' => $this->defaultMailContent(),
            'subject' => $this->defaultSubject(),
        ];
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return parent::via($notifiable);
    }
}
