<?php

namespace DaydreamLab\User\Services\Asset;

use DaydreamLab\User\Repositories\Asset\AssetRepository;
use DaydreamLab\JJAJ\Services\BaseService;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;


class AssetService extends BaseService
{
    protected $type = 'Asset';

    public function __construct(AssetRepository $repo)
    {
        parent::__construct($repo);
    }


    public function getApis($id)
    {
        $asset = $this->find($id);
        $this->status =  Str::upper(Str::snake($this->type.'GetApisSuccess'));;
        $this->response = $asset->groups;

        return $asset->apis;
    }


    public function getGroups($id)
    {
        $asset = $this->find($id);
        $this->status =  Str::upper(Str::snake($this->type.'GetGroupsSuccess'));;
        $this->response = $asset->groups;

        return $asset->groups;
    }


    public function store(Collection $input)
    {
        return parent::storeNested($input); // TODO: Change the autogenerated stub
    }
}
